name: WDLCompanionGriefPreventionSupport
main: wdl.griefprevention.GriefPreventionSupportPlugin
version: 1.0.0
author: Pokechu22
depend: [WDLCompanion, GriefPrevention]
website: http://dev.bukkit.org/bukkit-plugins/wdl-companion-griefprevention-support/
description: Adds a new ChunkOverride type, "Owned GriefPrevention claims", which allows players to download in their GriefPrevention claims.